### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by ofanoyi** [mdsufz/MuDoGeR#11]
File "/anaconda3/env/mudoger_env/dependencies/mdcheck.py", line 21, in <module>
 id, filepath, group=l.strip().split(sep)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by ofanoyi** [comment]
installation works well...but still some issues...thanks for taking a look..

Traceback (most recent call last):
  File "/anaconda3/envs/mudoger_env/dependencies/mdcheck.py", line 21, in <module>
    id,filepath,group=l.strip().split(sep)
ValueError: not enough values to unpack (expected 3, got 2)

mudoger preprocess
-> Running QC
---------- STARTING MODULE 1-1 QC
Not a conda environment: /anaconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env
-> Running khmer pred
---------- STARTING MODULE 1-2 KMER
Not a conda environment: /anaconda3/envs/mudoger_env/dependencies/conda/envs/khmer_env
unique-kmers.py: command not found
unique-kmers.py: command not found
cat: /media/seqdata1/MuDoGeR/khmer/kmer-33: No such file or directory
cat: /media/seqdata1/MuDoGeR/khmer/kmer-55: No such file or directory
Error in if (kmer_55_unique > 0) { : 
  missing value where TRUE/FALSE needed
Calls: as.data.frame -> t -> apply -> FUN
Execution halted
cat: metaspades_prediction.tsv: No such file or directory
/media/seqdata1/MuDoGeR
“end predict_mem_input”
-> Running assembly
Not a conda environment: /anaconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env
metawrap: command not found
assembly didnt work. please check your resources
-> module 1 (preprocess and assembly) is finished

**Comment by bramvandijk88** [comment]
> File "/anaconda3/env/mudoger_env/dependencies/mdcheck.py", line 21, in id, filepath, group=l.strip().split(sep) ValueError: not enough values to unpack (expected 3, got 2)

I am experiencing this error too.

**Comment by yankuosun** [comment]
I am experiencing this error too. But it ran well in module 1 and I would like to provide my remote account to check this problem. anyone help？

**Comment by JotaKas** [comment]
Dears,

The ValueError: not enough values to unpack (expected 3, got 2) comes from the mdcheck.py script, and can be ignored if the pipeline continued immediately after. Soon an update is coming. 


The other errors that @ofanoyi looks to be regarding the conda itself. The conda may not be properly available and the installation proceeded incorrectly since it depends on conda in several steps.

@ofanoyi could you please make sure your conda is working by manually creating any environment? 
Once you are sure conda is working and can properly activate environments, please delete the mudoger_env environment and try installing it again.

An update with a few improvements in the installation procedure is on the way and should be online in the next few days.
